const $=id=>document.getElementById(id);let clinicOpen=location.hash==='#clinic',saved={done:[],drafts:{}};try{saved={...saved,...JSON.parse(localStorage.getItem('sql-studio-v1')||'{}')};if(!Array.isArray(saved.done)||typeof saved.drafts!=='object'||!saved.drafts)throw Error();}catch{saved={done:[],drafts:{}};}if(saved.dialect!=='tsql-v1'){delete saved.drafts[4];saved.done=saved.done.filter(i=>i!==4);saved.dialect='tsql-v1';}if(saved.curriculum!=='levels-v1'){saved.done=saved.done.map(i=>lessons.findIndex(l=>l.legacy===i)).filter(i=>i>=0);saved.drafts=Object.fromEntries(Object.entries(saved.drafts).map(([i,v])=>[lessons.findIndex(l=>l.legacy===Number(i)),v]).filter(([i])=>i>=0));saved.curriculum='levels-v1';}let current=Math.max(0,Math.min(lessons.length-1,Number(location.hash.slice(1))||0)),busy=false,worker,seq=0;const pending=new Map();
function startWorker(){worker=new Worker('worker.js');worker.onmessage=({data})=>{const p=pending.get(data.id);if(p){clearTimeout(p.timer);pending.delete(data.id);data.error?p.reject(Error(data.error)):p.resolve(data);}};worker.onerror=()=>{for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('SQL engine could not load. Reconnect and reload the app.'));}pending.clear();};}startWorker();
function ask(payload){return new Promise((resolve,reject)=>{const id=++seq;const timer=setTimeout(()=>{worker.terminate();for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('Query timed out. Simplify the query and try again.'));}pending.clear();startWorker();},payload.kind==='preview'?60000:8000);pending.set(id,{resolve,reject,timer});worker.postMessage({...payload,id});});}
function persist(){try{localStorage.setItem('sql-studio-v1',JSON.stringify(saved));}catch{toast('Storage is unavailable. Progress will last only for this visit.');}}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,5000);}
function table(result,target){target.replaceChildren();if(!result)return;const table=document.createElement('table'),head=table.createTHead().insertRow();for(const c of result.columns){const th=document.createElement('th');th.textContent=c;head.append(th);}const body=table.createTBody();for(const row of result.values){const tr=body.insertRow();for(const v of row){tr.insertCell().textContent=v===null?'NULL':String(v);}}target.append(table);}
function navigation(){const count=lessons.filter((_,i)=>saved.done.includes(i)).length;$('progress').value=count;$('percent').textContent=Math.round(count/lessons.length*100)+'%';$('progress-text').textContent=`${count} of ${lessons.length} complete`;$('lessons').replaceChildren();lessons.forEach((l,i)=>{if(l.level!==lessons[current].level)return;const b=document.createElement('button');b.className='lesson'+(i===current?' active':'')+(saved.done.includes(i)?' complete':'');b.setAttribute('aria-current',i===current?'step':'false');const n=document.createElement('span');n.className='num';n.textContent=saved.done.includes(i)?'✓':String(l.position).padStart(2,'0');b.append(n,document.createTextNode(l.short));b.onclick=()=>selectLesson(i);$('lessons').append(b);});}
function selectLesson(i){if(busy)return;clinicOpen=false;document.body.classList.remove('clinic-mode');current=i;location.hash=String(i);const l=lessons[i];$('crumb').textContent=l.short;$('lesson-number').textContent=`LESSON ${String(l.position).padStart(2,'0')} / ${lessons.filter(item=>item.level===l.level).length}`;$('title').textContent=l.title;$('explanation').innerHTML='<p>'+l.body+'</p>';renderCourse(l);$('walkthrough').replaceChildren(...l.steps.map(step=>{const li=document.createElement('li');li.textContent=step;return li;}));$('pitfall').textContent=l.pitfall;$('example').textContent=l.example;$('task').textContent=l.task;$('hint').textContent=l.hint;$('hint').hidden=true;$('editor').value=saved.drafts[i]??l.starter??'SELECT *\nFROM students;';$('previous').disabled=i===0;$('next').disabled=i===lessons.length-1;$('results').replaceChildren();$('feedback').className='';$('feedback').textContent=saved.done.includes(i)?'You completed this lesson. Try another way to solve it.':'Run your query to see what you discover.';$('result-meta').textContent='Your output appears here';navigation();}
async function preview(){try{const t=$('table-select').value;const r=await ask({kind:'preview',table:t});table(r.results[0],$('dataset'));$('schema').textContent=t==='students'?'8 rows · course_id → courses.id':'4 rows · id is the primary key';$('run').disabled=false;$('run').textContent='▶ Run query';}catch(e){$('feedback').textContent=e.message;}}
async function run(){if(busy||window.examActive)return;const sql=$('editor').value;if(!sql.trim()){toast('Write a SQL query first.');return;}busy=true;$('run').disabled=true;$('run').textContent='Running…';const started=performance.now();try{const result=await ask({kind:'query',sql,lesson:current});table(result.results.at(-1),$('results'));$('result-meta').textContent=`${result.results.at(-1)?.values.length||0} rows · ${Math.round(performance.now()-started)} ms`;$('feedback').className=result.passed?'success':'';$('feedback').textContent=result.passed?'✓ Nicely done! Your answer is correct. Continue to the next lesson.':'Your query ran. The result doesn’t match the challenge yet. Check the requested columns and rows, or try a hint.';saved.stats??={queries:0};saved.stats.queries++;if(result.passed){if(!saved.done.includes(current))saved.done.push(current);persist();navigation();renderCourse(lessons[current]);if(saved.done.length===lessons.length)$('feedback').textContent='✓ All 30 lessons complete! You’ve built a solid SQL foundation. Revisit any lesson to keep practising.';}persist();updateDashboard();return{passed:result.passed,rows:result.results.at(-1)?.values.length||0};}catch(e){$('feedback').className='error';$('feedback').textContent='SQL error: '+e.message;$('results').replaceChildren();$('result-meta').textContent='Query needs attention';return{error:e.message};}finally{busy=false;$('run').disabled=false;$('run').textContent='▶ Run query';}}
$('run').onclick=run;$('editor').oninput=()=>{saved.drafts[current]=$('editor').value;persist();};$('editor').onkeydown=e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();run();}if(e.key==='Tab'){e.preventDefault();const el=e.target;el.setRangeText('  ',el.selectionStart,el.selectionEnd,'end');el.dispatchEvent(new Event('input'));}};$('reset').onclick=()=>{if(busy)return;delete saved.drafts[current];persist();selectLesson(current);};$('previous').onclick=()=>selectLesson(Math.max(0,current-1));$('next').onclick=()=>selectLesson(Math.min(lessons.length-1,current+1));$('hint-button').onclick=()=>{$('hint').hidden=!$('hint').hidden;};$('table-select').onchange=preview;window.onhashchange=()=>{if(location.hash==='#clinic'){showClinic();return;}const i=Number(location.hash.slice(1));if(Number.isInteger(i)&&i>=0&&i<lessons.length&&i!==current)selectLesson(i);};selectLesson(current);preview();if(clinicOpen)showClinic();
let cached=false;
function connectionLabel(){ $('offline').textContent=navigator.onLine?(cached?'Online · offline access saved':'Online · preparing offline access'):(cached?'Offline · saved lessons available':'Offline · reconnect to save lessons'); }
connectionLabel();window.addEventListener('online',connectionLabel);window.addEventListener('offline',connectionLabel);
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{cached=true;connectionLabel();}).catch(()=>{$('offline').textContent=navigator.onLine?'Online · offline access unavailable':'Offline';});}
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'run_sql_exercise',description:'Run a read-only SQL query against the current lesson and show feedback.',inputSchema:{type:'object',properties:{sql:{type:'string'}},required:['sql'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(typeof input?.sql!=='string'||!input.sql.trim()||busy||window.examActive)throw Error('Provide a nonempty SQL query while the editor is idle.');$('editor').value=input.sql;saved.drafts[current]=input.sql;persist();return await run();}})).catch(()=>{});}catch{}}

function showClinic(){clinicOpen=true;document.body.classList.add('clinic-mode');location.hash='clinic';$('course-name').textContent='Query clinic · Build, understand and fix SQL';$('course-intro').textContent='Take this section after Beginner and before Intermediate. Learn the structure of a query, why SQL is written in clauses, and how to work through errors without guessing.';$('prerequisite').textContent='Complete the Beginner path first, then use this guide before starting Intermediate.';$('outcomes').replaceChildren(...['The job of SELECT, FROM, WHERE, GROUP BY, HAVING and ORDER BY.','Why SQL uses separate clauses and a logical processing order.','How to read error messages as clues.','A repeatable checklist for finding and correcting mistakes.'].map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));$('query-clinic').open=true;$('level-heading').textContent='Query clinic';renderCourseTabs();}function renderCourse(lesson){
 const c=courses.find(c=>c.id===lesson.level);$('course-name').textContent=c.name+' · '+c.subtitle;$('course-intro').textContent=c.intro;$('prerequisite').textContent=c.prerequisite;$('level-badge').textContent=c.name+' · '+lesson.minutes+' MIN';$('level-heading').textContent=c.name+' lessons';$('progress').max=lessons.length;
 $('outcomes').replaceChildren(...c.outcomes.map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));
 renderCourseTabs(c.id);
}
function renderCourseTabs(selected){const tabs=[];courses.forEach((course,index)=>{const group=lessons.filter(l=>l.level===course.id);const done=group.filter(l=>saved.done.includes(lessons.indexOf(l))).length;const button=document.createElement('button');button.className='course-tab'+(course.id===selected&&!clinicOpen?' selected':'');button.setAttribute('aria-pressed',String(course.id===selected&&!clinicOpen));button.textContent=course.name+' · '+done+'/'+group.length;button.onclick=()=>{const next=lessons.findIndex(l=>l.level===course.id&&!saved.done.includes(lessons.indexOf(l)));selectLesson(next<0?lessons.findIndex(l=>l.level===course.id):next);};tabs.push(button);if(index===0){const clinic=document.createElement('button');clinic.className='course-tab clinic-tab'+(clinicOpen?' selected':'');clinic.setAttribute('aria-pressed',String(clinicOpen));clinic.textContent='Query clinic · Required bridge';clinic.onclick=showClinic;tabs.push(clinic);}});$('course-tabs').replaceChildren(...tabs);}

function completedCount(){return lessons.filter((_,i)=>saved.done.includes(i)).length;}
function updateDashboard(){
 const count=completedCount(), lesson=lessons[current], percent=Math.round(count/lessons.length*100);
 saved.stats??={queries:0};
 $('dashboard-percent').textContent=percent+'%';$('dashboard-progress').value=count;$('dashboard-progress-copy').textContent=`${count} of ${lessons.length} lessons completed`;$('dashboard-complete-count').textContent=`${count} / ${lessons.length}`;
 $('dashboard-current-title').textContent=lesson.title;$('dashboard-current-copy').textContent=lesson.task;$('dashboard-current-position').textContent=`Lesson ${current+1} of ${lessons.length}`;$('dashboard-current-level').textContent=lesson.level;
 $('dashboard-queries').textContent=saved.stats.queries||0;$('dashboard-challenges').textContent=count;$('dashboard-level').textContent=lessons[current].level;
 const courseStates=courses.map(course=>{const group=lessons.filter(l=>l.level===course.id);const done=group.filter(l=>saved.done.includes(lessons.indexOf(l))).length;return `<div class="path-row ${course.id===lesson.level?'active':''}"><span class="path-dot">${done===group.length?'✓':course.id===lesson.level?'●':'○'}</span><div><b>${course.name}</b><small>${done} of ${group.length} lessons complete</small></div><span>${done===group.length?'Complete':course.id===lesson.level?'In progress':'Up next'}</span></div>`;}).join('');
 $('dashboard-path').innerHTML=courseStates;
}
function showDashboard(){document.body.classList.remove('clinic-mode');$('learning-view').hidden=true;$('exam-page').hidden=true;$('dashboard-page').hidden=false;updateDashboard();}
function showLearning(){ $('dashboard-page').hidden=true;$('exam-page').hidden=true;$('learning-view').hidden=false;selectLesson(current); }
$('dashboard-view').onclick=showDashboard;
$('learn-view').onclick=showLearning;
$('dashboard-continue').onclick=showLearning;
$('dashboard-playground').onclick=showLearning;
$('dashboard-lesson').onclick=showLearning;
$('dashboard-clinic').onclick=()=>{showLearning();showClinic();};
function showWelcome(){document.body.classList.remove('clinic-mode');$('learning-view').hidden=true;$('exam-page').hidden=true;$('dashboard-page').hidden=true;$('welcome-page').hidden=false;}
function openSignup(){ $('signup-dialog').showModal(); }
$('welcome-view').onclick=showWelcome;
$('welcome-start').onclick=showDashboard;
$('welcome-signup').onclick=openSignup;
$('signup-close').onclick=()=>$('signup-dialog').close();
function friendlyAuthError(error){const code=error?.code||'';if(code.includes('email-already-in-use'))return 'An account already uses this email. Choose “I already have an account.”';if(code.includes('invalid-credential')||code.includes('wrong-password'))return 'That email or password is not correct.';if(code.includes('weak-password'))return 'Use a password with at least 6 characters.';if(code.includes('popup-closed'))return 'Google sign-in was closed before it finished.';return error?.message||'Sign-in could not finish. Please try again.';}
async function finishAuth(work){try{const user=await work();$('signup-dialog').close();toast(`Welcome${user.displayName?`, ${user.displayName}`:''}. Your learner account is ready.`);showDashboard();}catch(error){toast(friendlyAuthError(error));}}
$('google-signin').onclick=()=>finishAuth(()=>window.sqlStudioAuth?.google()??Promise.reject(Error('Account service is still loading. Please try again.')));
$('email-signin').onclick=()=>{const name=$('signup-name').value.trim(),email=$('signup-email').value.trim(),password=$('signup-password').value;if(!name||!email||!password){toast('Enter your name, email address and password.');return;}finishAuth(()=>window.sqlStudioAuth?.register(name,email,password)??Promise.reject(Error('Account service is still loading. Please try again.')));};
$('email-login').onclick=()=>{const email=$('signup-email').value.trim(),password=$('signup-password').value;if(!email||!password){toast('Enter your email address and password.');return;}finishAuth(()=>window.sqlStudioAuth?.login(email,password)??Promise.reject(Error('Account service is still loading. Please try again.')));};
window.addEventListener('sqlstudioauthready',event=>{const user=event.detail.user;if(user){saved.user={name:user.displayName||'',email:user.email||''};persist();}});
$('learn-view').addEventListener('click',()=>{$('welcome-page').hidden=true;});
$('exam-view').addEventListener('click',()=>{$('welcome-page').hidden=true;});
showWelcome();
