// Local practice assessment. No media is recorded or transmitted.
const EXAM_KEY='sql-studio-exam-v1', PASS_MARK=80, DURATION=45*60*1000;
let attempt=null,media=null,micContext=null,micFrame=0,examTimer=null,questionIndex=0,examBusy=false,lastIncident=0;
window.examActive=false;
try{attempt=JSON.parse(localStorage.getItem(EXAM_KEY)||'null');if(attempt&&(!Array.isArray(attempt.answers)||attempt.answers.length!==examQuestions.length||!attempt.answers.every(a=>typeof a==='string')||!Array.isArray(attempt.events)||typeof attempt.name!=='string'||!Number.isFinite(attempt.deadline)||!['active','submitted'].includes(attempt.status)||(attempt.status==='submitted'&&(!Array.isArray(attempt.results)||attempt.results.length!==examQuestions.length))))attempt=null;}catch{}
function examSave(){try{localStorage.setItem(EXAM_KEY,JSON.stringify(attempt));}catch{toast('Exam storage is unavailable. Keep this page open and download your report at the end.');}}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function examButton(label,fn,cls){const b=el('button',label,cls);b.type='button';b.onclick=fn;return b;}
function examNotice(text){const target=$('exam-message');if(target)target.textContent=text;else toast(text);}
function stopMedia(){if(media)media.getTracks().forEach(t=>t.stop());media=null;cancelAnimationFrame(micFrame);if(micContext){micContext.close().catch(()=>{});micContext=null;}}
function examHome(){
 if(window.examActive)return;
 $('learning-view').hidden=true;$('exam-page').hidden=false;$('exam-page').replaceChildren();
 const page=$('exam-page'),intro=el('div',undefined,'exam-intro');intro.append(el('div','FINAL ASSESSMENT','eyebrow'),el('h1','Put your SQL skills to work'),el('p','12 practical SQL questions across Beginner, Intermediate and Advanced. You have 45 minutes. Pass with at least 80% (10 of 12 correct). Learning and the exam are free. Certificate fee: US$5. A certificate is issued only after you pass and payment is confirmed.'));
 const rules=el('ul');['Use your own work. Complete the course before attempting the exam.','Use a desktop browser with fullscreen support, a camera and a microphone.','Tab changes, loss of focus, fullscreen exits and device interruptions produce warnings and a local event log. They are not automatically treated as cheating.','Camera video and microphone activity stay on your device. Nothing is recorded, uploaded or watched remotely.','This is a self-assessed practice exam. Results and logs are stored locally and are not independently verified.'].forEach(t=>rules.append(el('li',t)));intro.append(rules);page.append(intro);
 if(attempt?.status==='submitted'){renderExamResult();return;}
 const form=el('div',undefined,'exam-setup');const label=el('label','Name to appear on your certificate');label.htmlFor='candidate-name';const input=el('input');input.id='candidate-name';input.maxLength=80;input.autocomplete='name';input.value=attempt?.name||'';if(attempt?.status==='active')input.readOnly=true;
 const consentLabel=el('label',undefined,'consent-label');const consent=el('input');consent.type='checkbox';consent.id='exam-consent';consentLabel.append(consent,document.createTextNode('I understand the exam rules and agree to local camera/microphone checks and event logging.'));
 const preview=el('video');preview.id='camera-preview';preview.autoplay=true;preview.muted=true;preview.playsInline=true;preview.setAttribute('aria-label','Your camera preview');const meterLabel=el('label','Microphone activity');meterLabel.htmlFor='mic-meter';const meter=el('meter');meter.id='mic-meter';meter.min=0;meter.max=100;meter.value=0;
 const message=el('p','No camera or microphone access has been requested yet.','muted');message.id='exam-message';message.setAttribute('role','status');
 const check=examButton('1. Check camera & microphone',prepareDevices);check.id='device-check';const start=examButton(attempt?.status==='active'?'2. Resume in fullscreen':'2. Start exam in fullscreen',startExam,'run');start.id='start-exam';start.disabled=true;
 if(attempt?.status==='active')form.append(el('p','An unfinished attempt was found. Its original deadline still applies. Resuming records the interruption; your saved answers are kept.'));
 form.append(label,input,consentLabel,preview,meterLabel,meter,message,check,start,examButton('Back to lessons',showLessons));page.append(form);
}
async function prepareDevices(){
 if(!$('exam-consent').checked){examNotice('Please read and accept the local device-check rules first.');return;}
 if(!$('candidate-name').value.trim()){examNotice('Enter your name before the device check.');return;}
 if(!document.fullscreenEnabled||!document.documentElement.requestFullscreen){examNotice('This browser does not support the required fullscreen mode. Try a supported desktop browser.');return;}
 if(!navigator.mediaDevices?.getUserMedia){examNotice('Camera and microphone access require a supported browser and HTTPS.');return;}
 stopMedia();$('device-check').disabled=true;examNotice('Waiting for your camera and microphone permission…');
 try{media=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:320},height:{ideal:180}},audio:true});if($('exam-page').hidden){stopMedia();return;}$('camera-preview').srcObject=media;
  try{micContext=new AudioContext();await micContext.resume();const source=micContext.createMediaStreamSource(media),analyser=micContext.createAnalyser();analyser.fftSize=256;source.connect(analyser);const samples=new Uint8Array(analyser.fftSize);const tick=()=>{analyser.getByteTimeDomainData(samples);let sum=0;for(const v of samples)sum+=(v-128)**2;const meter=$('mic-meter');if(meter)meter.value=Math.min(100,Math.sqrt(sum/samples.length)*4);micFrame=requestAnimationFrame(tick);};tick();}catch{examNotice('Microphone access was granted, but this browser cannot display its activity meter.');}
  for(const track of media.getTracks()){track.onended=()=>{if(window.examActive)logIncident('device-ended',track.kind+' access ended');if($('start-exam'))$('start-exam').disabled=true;};track.onmute=()=>{if(window.examActive)logIncident('device-muted',track.kind+' was interrupted');};}
  $('start-exam').disabled=false;examNotice('Devices connected. Check that your video is visible and speak to test the microphone meter. No recording is made.');
 }catch(e){stopMedia();examNotice(e.name==='NotAllowedError'?'Permission was denied. Allow camera and microphone in your browser settings, then try again.':'Could not access both devices. Check that a camera and microphone are connected and not in use elsewhere.');}
 finally{if($('device-check'))$('device-check').disabled=false;}
}
async function startExam(){
 if(!$('exam-consent').checked||!media||media.getVideoTracks()[0]?.readyState!=='live'||media.getAudioTracks()[0]?.readyState!=='live'){examNotice('Complete the device check and accept the rules before starting.');return;}
 const name=$('candidate-name').value.trim();if(!name){examNotice('Enter your name.');return;}
 try{await document.documentElement.requestFullscreen();}catch{examNotice('Fullscreen was not enabled. Click Start again or use a supported desktop browser.');return;}
 if(attempt?.status==='active'){attempt.events.push({at:new Date().toISOString(),type:'resumed',detail:'Exam resumed after leaving or reloading the page.'});}
 else attempt={id:crypto.randomUUID(),name,status:'active',startedAt:Date.now(),deadline:Date.now()+DURATION,answers:examQuestions.map(()=>''),events:[],version:'course-30-v1'};
 window.examActive=true;examSave();renderExam();examTimer=setInterval(updateTimer,1000);updateTimer();
}
function renderExam(){
 const page=$('exam-page');page.replaceChildren();const header=el('div',undefined,'exam-top');const clock=el('strong');clock.id='exam-clock';const warning=el('div',undefined,'exam-warning');warning.id='exam-warning';warning.setAttribute('role','alert');warning.hidden=true;
 header.append(el('h1','SQL final assessment'),clock,examButton('Submit exam',()=>submitExam(false)));page.append(header,warning);
 const devices=el('div',undefined,'exam-devices');const video=el('video');video.autoplay=true;video.muted=true;video.playsInline=true;video.srcObject=media;devices.append(video,el('p','Camera and microphone active locally · No recording'),examButton('Return to fullscreen',async()=>{try{await document.documentElement.requestFullscreen();}catch{toast('Fullscreen could not be entered.');}}));page.append(devices);
 const nav=el('nav',undefined,'exam-question-nav');nav.setAttribute('aria-label','Exam questions');examQuestions.forEach((_,i)=>{const b=examButton(String(i+1),()=>{if(examBusy)return;questionIndex=i;renderQuestion();});b.id='exam-q-'+i;nav.append(b);});page.append(nav);
 const work=el('div',undefined,'exam-work');work.id='exam-work';page.append(work);page.append(el('p','Available tables: students(id, name, city, age, score, course_id) and courses(id, title). Use the same sample data as the lessons. Each question is worth one mark.','muted'));renderQuestion();
}
function renderQuestion(){const q=examQuestions[questionIndex],work=$('exam-work');work.replaceChildren();work.append(el('div',`${q.level} · Question ${questionIndex+1} of ${examQuestions.length}`,'eyebrow'),el('h2',q.task));const label=el('label','Your SQL answer');label.htmlFor='exam-editor';const editor=el('textarea');editor.id='exam-editor';editor.spellcheck=false;editor.value=attempt.answers[questionIndex];editor.oninput=()=>{attempt.answers[questionIndex]=editor.value;examSave();updateQuestionNav();};const results=el('div',undefined,'table-wrap');results.id='exam-output';const msg=el('p','Run your query to inspect its output. Correctness is shown after submission.');msg.id='exam-message';msg.setAttribute('role','status');const controls=el('div',undefined,'exam-controls');controls.append(examButton('Run query',examRun,'run'),examButton('Previous',()=>{if(!examBusy&&questionIndex>0){questionIndex--;renderQuestion();}}),examButton('Next',()=>{if(!examBusy&&questionIndex<examQuestions.length-1){questionIndex++;renderQuestion();}}));work.append(label,editor,controls,msg,results);updateQuestionNav();}
function updateQuestionNav(){examQuestions.forEach((_,i)=>{const b=$('exam-q-'+i);if(b){b.className=(i===questionIndex?'selected ':'')+(attempt.answers[i].trim()?'answered':'');b.setAttribute('aria-label',`Question ${i+1}${attempt.answers[i].trim()?', answered':''}`);b.setAttribute('aria-current',i===questionIndex?'step':'false');}});}
async function examRun(){if(examBusy||attempt.status!=='active')return;if(Date.now()>=attempt.deadline){await submitExam(true);return;}const sql=attempt.answers[questionIndex];if(!sql.trim()){examNotice('Write a query first.');return;}examBusy=true;examNotice('Running…');try{const data=await ask({kind:'query',sql,lesson:-1});if(attempt.status==='active'){table(data.results.at(-1),$('exam-output'));examNotice(`${data.results.at(-1)?.values.length||0} rows returned. Answer checking happens at submission.`);}}catch(e){if(attempt.status==='active')examNotice('Query error: '+e.message);}finally{examBusy=false;}}
function updateTimer(){if(!window.examActive)return;const remaining=Math.max(0,attempt.deadline-Date.now());const secs=Math.ceil(remaining/1000);if($('exam-clock'))$('exam-clock').textContent=`${Math.floor(secs/60)}:${String(secs%60).padStart(2,'0')} remaining`;if(remaining===0)submitExam(true);}
function logIncident(type,detail){if(!window.examActive||attempt?.status!=='active')return;const now=Date.now();attempt.events.push({at:new Date(now).toISOString(),type,detail});examSave();if(now-lastIncident>1500){lastIncident=now;const warning=$('exam-warning');if(warning){warning.hidden=false;warning.textContent='Warning: '+detail+'. This event has been logged for review. Return to the exam and continue. It does not automatically change your score.';}}}
document.addEventListener('visibilitychange',()=>{if(document.hidden)logIncident('tab-hidden','The exam page was hidden or another tab was opened');});
window.addEventListener('blur',()=>logIncident('focus-lost','The exam window lost focus'));
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)logIncident('fullscreen-exit','Fullscreen was exited');});
window.addEventListener('beforeunload',event=>{if(window.examActive){logIncident('page-leave','An attempt was made to close or reload the exam');event.preventDefault();event.returnValue='';}});
window.addEventListener('pagehide',()=>{if(window.examActive)examSave();stopMedia();});
async function submitExam(automatic){
 if(attempt?.status!=='active'||attempt.submitting)return;
 if(!automatic){showSubmitDialog();return;}
 await finishExam();
}
function showSubmitDialog(){if($('submit-dialog'))return;const dialog=el('dialog');dialog.id='submit-dialog';const count=attempt.answers.filter(a=>a.trim()).length;dialog.append(el('h2','Submit your exam?'),el('p',`${count} of ${examQuestions.length} questions have an answer. After submission this attempt cannot be edited.`),examButton('Keep working',()=>{dialog.close();dialog.remove();}),examButton('Submit answers',async()=>{dialog.close();dialog.remove();await finishExam();},'run'));$('exam-page').append(dialog);dialog.addEventListener('cancel',()=>dialog.remove());dialog.showModal();}
async function finishExam(){
 if(attempt?.status!=='active'||attempt.submitting)return;attempt.submitting=true;window.examActive=false;clearInterval(examTimer);$('submit-dialog')?.remove();stopMedia();if(document.fullscreenElement)try{await document.exitFullscreen();}catch{}
 $('exam-page').replaceChildren(el('h1','Checking your answers…'));const results=[];
 for(let i=0;i<examQuestions.length;i++){if(!attempt.answers[i].trim()){results.push({correct:false,reason:'No answer'});continue;}try{const result=await ask({kind:'grade',sql:attempt.answers[i],question:i});results.push({correct:result.passed,reason:result.passed?'Correct':'Result does not match the requested output'});}catch(e){results.push({correct:false,reason:e.message});}}
 attempt.results=results;attempt.correct=results.filter(r=>r.correct).length;attempt.score=Math.round(attempt.correct/examQuestions.length*100);attempt.passed=attempt.score>=PASS_MARK;attempt.status='submitted';attempt.finishedAt=Date.now();delete attempt.submitting;examSave();examHome();
}
function downloadFile(content,type,name){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function renderExamResult(){const page=$('exam-page'),result=el('div',undefined,'exam-result');result.append(el('h2',attempt.passed?'Assessment passed':'Keep practising, then try again'),el('p',`${attempt.name}: ${attempt.correct}/${examQuestions.length} correct · ${attempt.score}% · Pass mark ${PASS_MARK}%`),el('p',`${attempt.events.length} recorded exam events. Events need human review; they are not proof of cheating.`));
 const list=el('ol');attempt.results.forEach((r,i)=>list.append(el('li',`${examQuestions[i].level}, question ${i+1}: ${r.correct?'Correct':r.reason}`)));result.append(list);
 if(attempt.passed){const notice=el('div',undefined,'certificate-notice');notice.append(el('h3','Certificate pending payment confirmation'),el('p','Certificate fee: US$5. Passing the exam does not issue a certificate automatically. Your payment must be confirmed first.'),el('p','Online payment and certificate verification are not connected yet. Contact your instructor for the next steps. This page does not collect payments or issue paid certificates.','muted'));result.append(notice);}
 result.append(examButton('Download exam report',()=>downloadFile(JSON.stringify({notice:'Local, student-controlled practice assessment. Not independently verified. No audio or video was recorded.',...attempt,questions:examQuestions.map(q=>({level:q.level,task:q.task}))},null,2),'application/json','sql-studio-exam-report.json')));
 const events=el('details');events.append(el('summary','Review exam event log'));const log=el('ol');attempt.events.forEach(e=>log.append(el('li',`${new Date(e.at).toLocaleString()}: ${e.detail}`)));events.append(log);result.append(events,examButton('Start a new attempt',()=>{attempt=null;examSave();questionIndex=0;examHome();}),examButton('Back to lessons',showLessons));page.append(result);
}
function showLessons(){if(window.examActive){toast('Submit your active exam before returning to lessons.');return;}stopMedia();$('exam-page').hidden=true;$('learning-view').hidden=false;}
$('exam-view').onclick=()=>{if(window.examActive){toast('Your exam is already in progress.');return;}examHome();};$('learn-view').onclick=showLessons;
