const seed = `CREATE TABLE students (id INTEGER PRIMARY KEY, name TEXT, city TEXT, age INTEGER, score INTEGER, course_id INTEGER);
INSERT INTO students VALUES (1,'Ada','Lagos',21,92,1),(2,'Tunde','Abuja',24,78,2),(3,'Chiamaka','Lagos',22,85,1),(4,'Ibrahim','Kano',20,67,3),(5,'Zainab','Abuja',23,95,2),(6,'Emeka','Enugu',25,81,NULL),(7,'Funke','Ibadan',21,74,3),(8,'David','Lagos',24,88,1);
CREATE TABLE courses (id INTEGER PRIMARY KEY, title TEXT); INSERT INTO courses VALUES (1,'Data Analytics'),(2,'Web Development'),(3,'Product Design'),(4,'Cybersecurity');`;
const lessons = [
{title:'Meet your first query',short:'Your first query',body:'A database stores information in <strong>tables</strong>. Each row is a record, and each column describes one part of it.<br><br><code>SELECT</code> chooses the columns you want. <code>FROM</code> tells SQL which table to read. An asterisk (<code>*</code>) means “all columns”.',example:'SELECT *\nFROM courses;',task:'Show every column and every row from the students table.',hint:'Start with SELECT *, then choose students after FROM.',answer:'SELECT * FROM students;',starter:'-- Explore the students table\nSELECT\nFROM students;'},
{title:'Choose what matters',short:'Select columns',body:'You rarely need every column. List the column names you want after <code>SELECT</code>, separated by commas. The results follow the column order you choose.',example:'SELECT name, city\nFROM students;',task:'Return only the name and score of every student, in that column order.',hint:'Replace the asterisk with name, score.',answer:'SELECT name, score FROM students;'},
{title:'Find the right rows',short:'Filter with WHERE',body:'Use <code>WHERE</code> to return only matching rows. Put text values in single quotes. SQL uses <code>=</code> to test equality and <code>&gt;</code>, <code>&lt;</code>, <code>&gt;=</code> for comparisons.',example:"SELECT * FROM students\nWHERE city = 'Abuja';",task:'Show all columns for students who live in Lagos.',hint:"Use WHERE city = 'Lagos'.",answer:"SELECT * FROM students WHERE city = 'Lagos';"},
{title:'Combine your conditions',short:'AND & OR',body:'<code>AND</code> requires both conditions to be true. <code>OR</code> requires at least one. Use parentheses when you mix them to make your intended grouping clear.',example:"SELECT * FROM students\nWHERE city = 'Abuja' AND score > 80;",task:'Show all columns for Lagos students with a score of at least 90.',hint:"Combine city = 'Lagos' AND score >= 90.",answer:"SELECT * FROM students WHERE city = 'Lagos' AND score >= 90;"},
{title:'Put results in order',short:'ORDER BY & LIMIT',body:'<code>ORDER BY</code> sorts your results. <code>ASC</code> is ascending and <code>DESC</code> is descending. Add <code>LIMIT</code> to keep only a fixed number of rows.',example:'SELECT name, age FROM students\nORDER BY age ASC\nLIMIT 2;',task:'Return the name and score of the top 3 students, highest score first.',hint:'Sort by score DESC, then LIMIT 3.',answer:'SELECT name, score FROM students ORDER BY score DESC LIMIT 3;',ordered:true},
{title:'Spot the unique values',short:'DISTINCT',body:'<code>DISTINCT</code> removes duplicate result rows. When selecting one column, you get a list of its unique values.',example:'SELECT DISTINCT course_id\nFROM students;',task:'List every distinct city in the students table.',hint:'Place DISTINCT before city.',answer:'SELECT DISTINCT city FROM students;'},
{title:'Search for a pattern',short:'Patterns with LIKE',body:'<code>LIKE</code> matches text patterns. <code>%</code> means any number of characters, and <code>_</code> means exactly one character. In this SQLite setup, LIKE is case-insensitive for basic English letters.',example:"SELECT * FROM students\nWHERE name LIKE 'T%';",task:'Return all columns for students whose name starts with A.',hint:"Use name LIKE 'A%'.",answer:"SELECT * FROM students WHERE name LIKE 'A%';"},
{title:'Turn rows into insights',short:'COUNT, AVG & SUM',body:'Aggregate functions summarize rows. <code>COUNT(*)</code> counts rows, <code>AVG(score)</code> calculates an average, and <code>SUM(score)</code> adds scores. Use <code>AS</code> to give a result column a helpful name.',example:'SELECT AVG(score) AS average_score\nFROM students;',task:'Count all students. Return one column named total_students.',hint:'Use COUNT(*) AS total_students.',answer:'SELECT COUNT(*) AS total_students FROM students;',names:true},
{title:'Make a summary per group',short:'GROUP BY',body:'<code>GROUP BY</code> collects rows with the same value so an aggregate can summarize each group. Select the group column alongside the aggregate.',example:'SELECT course_id, COUNT(*) AS total\nFROM students\nGROUP BY course_id;',task:'Return city and COUNT(*) AS total for each city.',hint:'Group by city and count the rows in each group.',answer:'SELECT city, COUNT(*) AS total FROM students GROUP BY city;',names:true},
{title:'Bring two tables together',short:'INNER JOIN',body:'<code>JOIN</code> connects related tables. The <code>ON</code> condition describes how rows match. Here, a student’s <code>course_id</code> matches a course’s <code>id</code>. INNER JOIN leaves out students without a matching course.',example:'SELECT students.name, courses.title\nFROM students\nJOIN courses ON students.course_id = courses.id;',task:'Return student name and course title for every student with a matching course.',hint:'Use the JOIN example above. The result has 7 rows.',answer:'SELECT students.name, courses.title FROM students JOIN courses ON students.course_id = courses.id;'},
{title:'Keep the missing matches',short:'LEFT JOIN & NULL',body:'<code>LEFT JOIN</code> keeps every row from the left table, even without a match. Missing values appear as <code>NULL</code>. Test missing values with <code>IS NULL</code>, not <code>= NULL</code>.',example:'SELECT students.name, courses.title\nFROM students\nLEFT JOIN courses ON students.course_id = courses.id;',task:'Return only the names of students who have no course assigned.',hint:'Filter students using WHERE course_id IS NULL.',answer:'SELECT name FROM students WHERE course_id IS NULL;'},
{title:'A query inside a query',short:'Subqueries',body:'A subquery is a query inside another query. Parentheses let you use its result in a comparison. It helps answer questions such as “Who scored above the class average?”',example:'SELECT name FROM students\nWHERE age > (SELECT AVG(age) FROM students);',task:'Return name and score for students scoring above the average score, highest score first.',hint:'Compare score to (SELECT AVG(score) FROM students), then ORDER BY score DESC.',answer:'SELECT name, score FROM students WHERE score > (SELECT AVG(score) FROM students) ORDER BY score DESC;',ordered:true}
];
if(typeof module !== 'undefined') module.exports={seed,lessons};
